### ISSUE TITLE
Nice idea and happy to help

### ISSUE THREAD

**Issue by jhollist** [jsta/sfpolymorph#1]
I like this idea, @jsta!  I was planning on re-doing lakemorpho in a tidy/sf compliant way.  Makes more sense to port most of the more generic shape metrics to its own package.  I would import this and just re-write the more lake specific types of metrics (e.g. depth estimates, volume, etc.) .

My time is short now, but will keep an eye here and if there are some small pieces you want to pawn off to me, let me know.

**Comment by lambdamoses** [comment]
Hi, I'm also interested in contributing, potentially doing Rcpp since my use case is spatial genomics where I want to compute morphological metrics on millions of cells. Still interested in collaboration?

**Comment by jsta** [comment]
@lambdamoses I'm not longer developing much in R these days. I use and recommend scikit-image `regionprops`:
https://scikit-image.org/docs/stable/api/skimage.measure.html?highlight=regionprops#skimage.measure.regionprops
